name: pc
version: '18-2'
summary: PC gadget for generic 32-bit devices
type: gadget
base: core18
description: |
    This gadget enables generic 32-bit pc devices to work with Ubuntu Core
architectures:
  - i386
grade: stable
confinement: strict
icon: icon.png

parts:
  grub:
    source: .
    plugin: make
    build-packages:
      - grub-pc-bin
        
