name: generic-i386
vendor: Sergio Schvezov <sergio.schvezov@canonical.com>
icon: meta/ubuntu.png
version: 1.1
type: oem

config:
    ubuntu-core:
        autopilot: true

oem:
    branding:
        name:  i386
        subname: generic

    hardware:
        bootloader: grub
        architecture: i386
        partition-layout: system-AB
