name: canonical-i386
vendor: Sergio Schvezov <sergio.schvezov@canonical.com>
icon: meta/ubuntu.png
version: 1.4
type: oem

config:
    ubuntu-core:
        autopilot: true

oem:
    branding:
        name:  i386
        subname: generic

    hardware:
        bootloader: grub
        architecture: i386
        partition-layout: minimal
        boot-assets:
            files:
                - path: grub.cfg
